import { COLORS, SIZES, FONTS } from "../constants/theme";

export default {
  container: {
    flex: 1,
    backgroundColor: COLORS.LightGray4,
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  renderItemTouchableOpacity: {
    padding: SIZES.padding,
    paddingBottom: SIZES.padding * 2,
    backgroundColor: COLORS.primary,
    borderRadius: SIZES.radius,
    alignItems: "center",
    justifyContent: "center",
    marginRight: SIZES.padding,
    ...styles.shadow,
  },
  viewCategories: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
  },
  styleFormArea: {
    width: "90%",
    borderColor: "#20232a",
    borderRadius: 6,
  },
  styleContainer: {
    flex: 1,
    padding: 25,
    backgroundColor: COLORS.white,
  },
  innerContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
  },
  titlePage: {
    fontSize: 30,
    textAlign: "center",
    fontWeight: "bold",
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    color: COLORS.brand,
  },
  subTitle: {
    fontFamily: FONTS.h3,
    marginBottom: 20,
    letterSpacing: 1,
    fontWeight: "bold",
    color: COLORS.bluishgrey,
  },
  styleButton: {
    backgroundColor: COLORS.brand,
    paddingTop: 15,
    paddingRight: 15,
    paddingBottom: 15,
    paddingLeft: 15,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
    marginVertical: 5,
    height: 60,
    fontFamily: FONTS.body4,
  },
  textButton: {
    fontSize: 16,
    color: COLORS.white,
    fontFamily: FONTS.body5,
  },
  messageBox: {
    fontSize: 13,
    textAlign: "center",
  },
  extraView: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  extraText: {
    justifyContent: "center",
    alignContent: "center",
    fontSize: 15,
    color: COLORS.bluishgrey,
  },
  linkText: {
    justifyContent: "center",
    alignItems: "center",
    fontFamily: FONTS.body5,
  },
  contentLinkText: {
    color: COLORS.brand,
    fontSize: 15,
    fontFamily: FONTS.body5,
  },
  leftIcon: {
    left: 15,
    top: 38,
    position: "absolute",
    zIndex: 1,
  },
  rightIcon: {
    right: 15,
    top: 38,
    position: "absolute",
    zIndex: 1,
  },
  styleInputTag: {
    color: COLORS.bluishgrey,
    fontSize: 13,
    textAlign: "left",
    fontFamily: "Ubuntu-Medium",
    borderColor: COLORS.DarkGray,
    borderRadius: 6,
  },
  textInputStyle: {
    borderColor: COLORS.DarkGray,
    borderRadius: 6,
    color: COLORS.LightGray2,
    paddingTop: 15,
    paddingRight: 55,
    paddingBottom: 15,
    paddingLeft: 55,
    fontSize: 16,
    height: 60,
    marginVertical: 3,
    marginBottom: 10,
    color: COLORS.bluishgrey,
    fontFamily: "Ubuntu-Light",
  },
  Line: {
    height: 1,
    width: "100%",
    marginVertical: 10,
    color: COLORS.MediumGray,
  },
};
